### ISSUE TITLE
BrowserWindow error.

### ISSUE THREAD

**Issue by dededo** [luckynumber21/simple.js#1]
TypeError: BrowserWindow is not a constructor
    at Object.<anonymous> (/Users/micahmanlapeg/Documents/simple.js-test/node_modules/simplefsm/src/electron.js:13:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/micahmanlapeg/Documents/simple.js-test/node_modules/simplefsm/src/simple.js:11:12)
    at Module._compile (module.js:570:32)

simple.js will update as soon electron fixes BrowserWindow.

**Comment by dededo** [comment]
Fixed in #10

**Comment by dededo** [comment]
Fixed in [#10](https://github.com/luckynumber21/simple.js/commit/6d034ec3934b27e4584df581b8a3430447d1df92).
