### ISSUE TITLE
Error: Module did not self-register.

### ISSUE THREAD

**Issue by dededo** [luckynumber21/simple.js#3]
```
Macintosh:simple.js micahmanlapeg$ node tests/ostest.js
module.js:597
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module did not self-register.
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/micahmanlapeg/Documents/simple.js/src/os.js:11:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
```

**Comment by dededo** [comment]
Fixed in [#18](https://github.com/luckynumber21/simple.js/commit/65fe80f9f3b00565b91ce8720f4dbd913cd5e831)
